### ISSUE TITLE
(edge case) from_anndata() failure on dataset containing numeric categoricals

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SingleCell#30]
I have an H5AD with two numeric categoricals.  from_anndata() fails to convert it.  I have confirmed these columns cause the failure (when I drop them and re-convert, it works fine).

Am finding quite a few datasets with this issue.  Category dtypes I've observed include int64, float64 and uint64.  Have not seen bool yet, but suspect it is possible.  It seems that all could be cast to their native types before saving, with no loss of information (much like is already done with string).

The obs columns:
```
In [27]: ad.obs.uint_categorical
Out[27]: 
index
AAACATACAACCAC-1     13
AAACATTGAGCTAC-1     72
AAACATTGATCAGC-1    107
AAACCGTGCTTCCG-1    192
AAACCGTGTATGCG-1     10
                   ... 
TTTCGAACTCTCAT-1    131
TTTCTACTGAGGCA-1    203
TTTCTACTTCCTCG-1    110
TTTGCATGAGAGGC-1    198
TTTGCATGCCTCAC-1    212
Name: uint_categorical, Length: 2638, dtype: category
Categories (256, uint64): [0, 1, 2, 3, ..., 252, 253, 254, 255]

In [28]: ad.obs.int_categorical
Out[28]: 
index
AAACATACAACCAC-1     13
AAACATTGAGCTAC-1     72
AAACATTGATCAGC-1    107
AAACCGTGCTTCCG-1    192
AAACCGTGTATGCG-1     10
                   ... 
TTTCGAACTCTCAT-1    131
TTTCTACTGAGGCA-1    203
TTTCTACTTCCTCG-1    110
TTTGCATGAGAGGC-1    198
TTTGCATGCCTCAC-1    212
Name: int_categorical, Length: 2638, dtype: category
Categories (256, int64): [0, 1, 2, 3, ..., 252, 253, 254, 255]
```

The failure:
```
START  SOMA.from_ann
  START  DECATEGORICALIZING
  FINISH DECATEGORICALIZING
  START  WRITING ./temp/out
    START  WRITING ./temp/out/X/data
    FINISH WRITING ./temp/out/X/data
    START  WRITING ./temp/out/obs
Traceback (most recent call last):
  File "/home/bruce/projects/TileDB-SingleCell/apis/python/temp/ingest_sweep.py", line 75, in <module>
    sys.exit(main())
  File "/home/bruce/projects/TileDB-SingleCell/apis/python/temp/ingest_sweep.py", line 21, in main
    sc.from_anndata(ad)
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledbsc/soma.py", line 68, in from_anndata
    self.write_tiledb_group(anndata)
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledbsc/soma.py", line 188, in write_tiledb_group
    obs_uri = self.write_obs_or_var(anndata.obs, "obs", 256)
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledbsc/soma.py", line 345, in write_obs_or_var
    tiledb.from_pandas(
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledb/dataframe_.py", line 442, in from_pandas
    _from_pandas(uri, dataframe, tiledb_args)
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledb/dataframe_.py", line 489, in _from_pandas
    column_infos = _get_column_infos(
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledb/dataframe_.py", line 182, in _get_column_infos
    column_infos[name] = ColumnInfo.from_values(column, varlen_types)
  File "/home/bruce/projects/TileDB-SingleCell/venv/lib/python3.9/site-packages/tiledb/dataframe_.py", line 103, in from_values
    raise NotImplementedError(
NotImplementedError: integer inferred dtype not supported
```

**Comment by bkmartinjr** [comment]
I'm guessing this is an inherent limitation in the `from_pands()` implementation.  In our own H5AD->TileDB conversion code, we don't use that API and instead manually convert each column of the dataframes, which is why we have not previously tripped over it.
